// EventAPI CloudEvent IDL
//
// 定义 CloudEvent 相关的类型和枚举，供 Transport 和 Sink 模块复用。
// 参考: https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: eventapi/v1/cloudevent.proto

package eventapiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 事件数据编码格式，编译时确定
type EventDataContentType int32

const (
	EventDataContentType_CONTENT_TYPE_UNSPECIFIED EventDataContentType = 0
	EventDataContentType_CONTENT_TYPE_JSON        EventDataContentType = 1
	EventDataContentType_CONTENT_TYPE_PROTOBUF    EventDataContentType = 2
	EventDataContentType_CONTENT_TYPE_AVRO        EventDataContentType = 3
)

// Enum value maps for EventDataContentType.
var (
	EventDataContentType_name = map[int32]string{
		0: "CONTENT_TYPE_UNSPECIFIED",
		1: "CONTENT_TYPE_JSON",
		2: "CONTENT_TYPE_PROTOBUF",
		3: "CONTENT_TYPE_AVRO",
	}
	EventDataContentType_value = map[string]int32{
		"CONTENT_TYPE_UNSPECIFIED": 0,
		"CONTENT_TYPE_JSON":        1,
		"CONTENT_TYPE_PROTOBUF":    2,
		"CONTENT_TYPE_AVRO":        3,
	}
)

func (x EventDataContentType) Enum() *EventDataContentType {
	p := new(EventDataContentType)
	*p = x
	return p
}

func (x EventDataContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventDataContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_eventapi_v1_cloudevent_proto_enumTypes[0].Descriptor()
}

func (EventDataContentType) Type() protoreflect.EnumType {
	return &file_eventapi_v1_cloudevent_proto_enumTypes[0]
}

func (x EventDataContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventDataContentType.Descriptor instead.
func (EventDataContentType) EnumDescriptor() ([]byte, []int) {
	return file_eventapi_v1_cloudevent_proto_rawDescGZIP(), []int{0}
}

// CloudEvent 消息结构
// 符合 CloudEvents 1.0.2 规范
// 参考: https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md
// Protobuf 格式: https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/formats/protobuf-format.md
type CloudEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CloudEvent ID，唯一标识符
	// 由 SDK 自动生成 UUID
	// 参考: https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 事件来源，标识事件发生的位置
	// 格式: URI 或 URN
	// 例如: "urn:eventapi:service:user-service", "/myapp/users"
	// 参考: https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#source
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// CloudEvents 规范版本
	// 固定值: "1.0"
	// 参考: https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#specversion
	SpecVersion string `protobuf:"bytes,3,opt,name=spec_version,json=specVersion,proto3" json:"spec_version,omitempty"`
	// 事件类型，唯一标识事件的类型和版本
	// 由 event_type 选项定义
	// 例如: "acme.user.created.v1"
	// 参考: https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#type
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	// 数据内容类型 (MIME type)
	// 由 Codec 决定，如:
	// - JSON Codec: "application/json"
	// - Protobuf Codec: "application/protobuf"
	// 参考: https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#datacontenttype
	DataContentType EventDataContentType `protobuf:"varint,5,opt,name=data_content_type,json=dataContentType,proto3,enum=eventapi.v1.EventDataContentType" json:"data_content_type,omitempty"`
	// 数据模式 (Schema URL)，指向数据的 schema 定义
	// 可选字段
	// 例如: "https://acme.com/schemas/user-created.json"
	// 参考: https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#dataschema
	DataSchema string `protobuf:"bytes,6,opt,name=data_schema,json=dataSchema,proto3" json:"data_schema,omitempty"`
	// 主题，标识事件相关的资源
	// 由 is_subject 标记的字段提取
	// 例如: "user.123", "order.456"
	// 参考: https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#subject
	Subject string `protobuf:"bytes,7,opt,name=subject,proto3" json:"subject,omitempty"`
	// 事件发生时间
	// 由 SDK 在发送时自动填充
	// 参考: https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#time
	Time *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
	// 扩展属性 (可选)
	// 用于添加自定义元数据，如 trace_id, tenant_id
	// 参考: https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#extension-context-attributes
	Extensions map[string]*CloudEvent_AttributeValue `protobuf:"bytes,9,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 事件数据负载
	// 由 Codec 编码后的字节数据
	// JSON Codec: UTF-8 编码的 JSON 字符串
	// Protobuf Codec: protobuf 序列化后的字节
	// 参考: https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#data
	Data          []byte `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudEvent) Reset() {
	*x = CloudEvent{}
	mi := &file_eventapi_v1_cloudevent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudEvent) ProtoMessage() {}

func (x *CloudEvent) ProtoReflect() protoreflect.Message {
	mi := &file_eventapi_v1_cloudevent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudEvent.ProtoReflect.Descriptor instead.
func (*CloudEvent) Descriptor() ([]byte, []int) {
	return file_eventapi_v1_cloudevent_proto_rawDescGZIP(), []int{0}
}

func (x *CloudEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CloudEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CloudEvent) GetSpecVersion() string {
	if x != nil {
		return x.SpecVersion
	}
	return ""
}

func (x *CloudEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CloudEvent) GetDataContentType() EventDataContentType {
	if x != nil {
		return x.DataContentType
	}
	return EventDataContentType_CONTENT_TYPE_UNSPECIFIED
}

func (x *CloudEvent) GetDataSchema() string {
	if x != nil {
		return x.DataSchema
	}
	return ""
}

func (x *CloudEvent) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CloudEvent) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *CloudEvent) GetExtensions() map[string]*CloudEvent_AttributeValue {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *CloudEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 扩展属性值类型
// 支持多种数据类型
type CloudEvent_AttributeValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Attr:
	//
	//	*CloudEvent_AttributeValue_Boolean
	//	*CloudEvent_AttributeValue_Integer
	//	*CloudEvent_AttributeValue_String_
	//	*CloudEvent_AttributeValue_Bytes
	//	*CloudEvent_AttributeValue_Uri
	//	*CloudEvent_AttributeValue_UriRef
	//	*CloudEvent_AttributeValue_Timestamp
	Attr          isCloudEvent_AttributeValue_Attr `protobuf_oneof:"attr"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudEvent_AttributeValue) Reset() {
	*x = CloudEvent_AttributeValue{}
	mi := &file_eventapi_v1_cloudevent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudEvent_AttributeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudEvent_AttributeValue) ProtoMessage() {}

func (x *CloudEvent_AttributeValue) ProtoReflect() protoreflect.Message {
	mi := &file_eventapi_v1_cloudevent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudEvent_AttributeValue.ProtoReflect.Descriptor instead.
func (*CloudEvent_AttributeValue) Descriptor() ([]byte, []int) {
	return file_eventapi_v1_cloudevent_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CloudEvent_AttributeValue) GetAttr() isCloudEvent_AttributeValue_Attr {
	if x != nil {
		return x.Attr
	}
	return nil
}

func (x *CloudEvent_AttributeValue) GetBoolean() bool {
	if x != nil {
		if x, ok := x.Attr.(*CloudEvent_AttributeValue_Boolean); ok {
			return x.Boolean
		}
	}
	return false
}

func (x *CloudEvent_AttributeValue) GetInteger() int32 {
	if x != nil {
		if x, ok := x.Attr.(*CloudEvent_AttributeValue_Integer); ok {
			return x.Integer
		}
	}
	return 0
}

func (x *CloudEvent_AttributeValue) GetString_() string {
	if x != nil {
		if x, ok := x.Attr.(*CloudEvent_AttributeValue_String_); ok {
			return x.String_
		}
	}
	return ""
}

func (x *CloudEvent_AttributeValue) GetBytes() []byte {
	if x != nil {
		if x, ok := x.Attr.(*CloudEvent_AttributeValue_Bytes); ok {
			return x.Bytes
		}
	}
	return nil
}

func (x *CloudEvent_AttributeValue) GetUri() string {
	if x != nil {
		if x, ok := x.Attr.(*CloudEvent_AttributeValue_Uri); ok {
			return x.Uri
		}
	}
	return ""
}

func (x *CloudEvent_AttributeValue) GetUriRef() string {
	if x != nil {
		if x, ok := x.Attr.(*CloudEvent_AttributeValue_UriRef); ok {
			return x.UriRef
		}
	}
	return ""
}

func (x *CloudEvent_AttributeValue) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Attr.(*CloudEvent_AttributeValue_Timestamp); ok {
			return x.Timestamp
		}
	}
	return nil
}

type isCloudEvent_AttributeValue_Attr interface {
	isCloudEvent_AttributeValue_Attr()
}

type CloudEvent_AttributeValue_Boolean struct {
	// 布尔值
	Boolean bool `protobuf:"varint,1,opt,name=boolean,proto3,oneof"`
}

type CloudEvent_AttributeValue_Integer struct {
	// 32位整数
	Integer int32 `protobuf:"varint,2,opt,name=integer,proto3,oneof"`
}

type CloudEvent_AttributeValue_String_ struct {
	// 字符串
	String_ string `protobuf:"bytes,3,opt,name=string,proto3,oneof"`
}

type CloudEvent_AttributeValue_Bytes struct {
	// 字节数组
	Bytes []byte `protobuf:"bytes,4,opt,name=bytes,proto3,oneof"`
}

type CloudEvent_AttributeValue_Uri struct {
	// URI
	Uri string `protobuf:"bytes,5,opt,name=uri,proto3,oneof"`
}

type CloudEvent_AttributeValue_UriRef struct {
	// URI Reference
	UriRef string `protobuf:"bytes,6,opt,name=uri_ref,json=uriRef,proto3,oneof"`
}

type CloudEvent_AttributeValue_Timestamp struct {
	// 时间戳
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3,oneof"`
}

func (*CloudEvent_AttributeValue_Boolean) isCloudEvent_AttributeValue_Attr() {}

func (*CloudEvent_AttributeValue_Integer) isCloudEvent_AttributeValue_Attr() {}

func (*CloudEvent_AttributeValue_String_) isCloudEvent_AttributeValue_Attr() {}

func (*CloudEvent_AttributeValue_Bytes) isCloudEvent_AttributeValue_Attr() {}

func (*CloudEvent_AttributeValue_Uri) isCloudEvent_AttributeValue_Attr() {}

func (*CloudEvent_AttributeValue_UriRef) isCloudEvent_AttributeValue_Attr() {}

func (*CloudEvent_AttributeValue_Timestamp) isCloudEvent_AttributeValue_Attr() {}

var file_eventapi_v1_cloudevent_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "eventapi.v1.event_type",
		Tag:           "bytes,50001,opt,name=event_type",
		Filename:      "eventapi/v1/cloudevent.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50002,
		Name:          "eventapi.v1.is_event_subject",
		Tag:           "varint,50002,opt,name=is_event_subject",
		Filename:      "eventapi/v1/cloudevent.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50004,
		Name:          "eventapi.v1.is_event_header",
		Tag:           "varint,50004,opt,name=is_event_header",
		Filename:      "eventapi/v1/cloudevent.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*EventDataContentType)(nil),
		Field:         50003,
		Name:          "eventapi.v1.event_data_content_type",
		Tag:           "varint,50003,opt,name=event_data_content_type,enum=eventapi.v1.EventDataContentType",
		Filename:      "eventapi/v1/cloudevent.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// event_type 选项编号: 50001
	// 声明此消息对应的 CloudEvent type 属性
	// 格式: {reverse-domain}.{event-name}.{version}
	// 例如: "acme.user.created.v1", "io.github.order.paid.v2"
	//
	// optional string event_type = 50001;
	E_EventType = &file_eventapi_v1_cloudevent_proto_extTypes[0]
	// event_data_content_type 选项编号: 50003
	// 声明此消息对应的 CloudEvent data_content_type
	// 默认: CONTENT_TYPE_JSON
	//
	// optional eventapi.v1.EventDataContentType event_data_content_type = 50003;
	E_EventDataContentType = &file_eventapi_v1_cloudevent_proto_extTypes[3]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// is_event_subject 选项编号: 50002
	// 标记此字段的值将提取为 CloudEvent 的 subject 属性
	// subject 用于标识事件所描述的资源
	// 例如: user_id 字段标记为 subject，则 "user.123" 成为 subject
	//
	// optional bool is_event_subject = 50002;
	E_IsEventSubject = &file_eventapi_v1_cloudevent_proto_extTypes[1]
	// is_event_header 选项编号: 50004
	//
	// optional bool is_event_header = 50004;
	E_IsEventHeader = &file_eventapi_v1_cloudevent_proto_extTypes[2]
)

var File_eventapi_v1_cloudevent_proto protoreflect.FileDescriptor

const file_eventapi_v1_cloudevent_proto_rawDesc = "" +
	"\n" +
	"\x1ceventapi/v1/cloudevent.proto\x12\veventapi.v1\x1a google/protobuf/descriptor.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x05\n" +
	"\n" +
	"CloudEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12!\n" +
	"\fspec_version\x18\x03 \x01(\tR\vspecVersion\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12M\n" +
	"\x11data_content_type\x18\x05 \x01(\x0e2!.eventapi.v1.EventDataContentTypeR\x0fdataContentType\x12\x1f\n" +
	"\vdata_schema\x18\x06 \x01(\tR\n" +
	"dataSchema\x12\x18\n" +
	"\asubject\x18\a \x01(\tR\asubject\x12.\n" +
	"\x04time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12G\n" +
	"\n" +
	"extensions\x18\t \x03(\v2'.eventapi.v1.CloudEvent.ExtensionsEntryR\n" +
	"extensions\x12\x12\n" +
	"\x04data\x18\n" +
	" \x01(\fR\x04data\x1ae\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.eventapi.v1.CloudEvent.AttributeValueR\x05value:\x028\x01\x1a\xed\x01\n" +
	"\x0eAttributeValue\x12\x1a\n" +
	"\aboolean\x18\x01 \x01(\bH\x00R\aboolean\x12\x1a\n" +
	"\ainteger\x18\x02 \x01(\x05H\x00R\ainteger\x12\x18\n" +
	"\x06string\x18\x03 \x01(\tH\x00R\x06string\x12\x16\n" +
	"\x05bytes\x18\x04 \x01(\fH\x00R\x05bytes\x12\x12\n" +
	"\x03uri\x18\x05 \x01(\tH\x00R\x03uri\x12\x19\n" +
	"\auri_ref\x18\x06 \x01(\tH\x00R\x06uriRef\x12:\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x00R\ttimestampB\x06\n" +
	"\x04attr*}\n" +
	"\x14EventDataContentType\x12\x1c\n" +
	"\x18CONTENT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CONTENT_TYPE_JSON\x10\x01\x12\x19\n" +
	"\x15CONTENT_TYPE_PROTOBUF\x10\x02\x12\x15\n" +
	"\x11CONTENT_TYPE_AVRO\x10\x03:@\n" +
	"\n" +
	"event_type\x12\x1f.google.protobuf.MessageOptions\x18ц\x03 \x01(\tR\teventType:I\n" +
	"\x10is_event_subject\x12\x1d.google.protobuf.FieldOptions\x18҆\x03 \x01(\bR\x0eisEventSubject:G\n" +
	"\x0fis_event_header\x12\x1d.google.protobuf.FieldOptions\x18Ԇ\x03 \x01(\bR\risEventHeader:{\n" +
	"\x17event_data_content_type\x12\x1f.google.protobuf.MessageOptions\x18ӆ\x03 \x01(\x0e2!.eventapi.v1.EventDataContentTypeR\x14eventDataContentTypeB\xab\x01\n" +
	"\x0fcom.eventapi.v1B\x0fCloudeventProtoP\x01Z:github.com/eventapi/eventapi-go/pkg/eventapi/v1;eventapiv1\xa2\x02\x03EXX\xaa\x02\vEventapi.V1\xca\x02\vEventapi\\V1\xe2\x02\x17Eventapi\\V1\\GPBMetadata\xea\x02\fEventapi::V1b\x06proto3"

var (
	file_eventapi_v1_cloudevent_proto_rawDescOnce sync.Once
	file_eventapi_v1_cloudevent_proto_rawDescData []byte
)

func file_eventapi_v1_cloudevent_proto_rawDescGZIP() []byte {
	file_eventapi_v1_cloudevent_proto_rawDescOnce.Do(func() {
		file_eventapi_v1_cloudevent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eventapi_v1_cloudevent_proto_rawDesc), len(file_eventapi_v1_cloudevent_proto_rawDesc)))
	})
	return file_eventapi_v1_cloudevent_proto_rawDescData
}

var file_eventapi_v1_cloudevent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_eventapi_v1_cloudevent_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_eventapi_v1_cloudevent_proto_goTypes = []any{
	(EventDataContentType)(0),           // 0: eventapi.v1.EventDataContentType
	(*CloudEvent)(nil),                  // 1: eventapi.v1.CloudEvent
	nil,                                 // 2: eventapi.v1.CloudEvent.ExtensionsEntry
	(*CloudEvent_AttributeValue)(nil),   // 3: eventapi.v1.CloudEvent.AttributeValue
	(*timestamppb.Timestamp)(nil),       // 4: google.protobuf.Timestamp
	(*descriptorpb.MessageOptions)(nil), // 5: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 6: google.protobuf.FieldOptions
}
var file_eventapi_v1_cloudevent_proto_depIdxs = []int32{
	0,  // 0: eventapi.v1.CloudEvent.data_content_type:type_name -> eventapi.v1.EventDataContentType
	4,  // 1: eventapi.v1.CloudEvent.time:type_name -> google.protobuf.Timestamp
	2,  // 2: eventapi.v1.CloudEvent.extensions:type_name -> eventapi.v1.CloudEvent.ExtensionsEntry
	3,  // 3: eventapi.v1.CloudEvent.ExtensionsEntry.value:type_name -> eventapi.v1.CloudEvent.AttributeValue
	4,  // 4: eventapi.v1.CloudEvent.AttributeValue.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 5: eventapi.v1.event_type:extendee -> google.protobuf.MessageOptions
	6,  // 6: eventapi.v1.is_event_subject:extendee -> google.protobuf.FieldOptions
	6,  // 7: eventapi.v1.is_event_header:extendee -> google.protobuf.FieldOptions
	5,  // 8: eventapi.v1.event_data_content_type:extendee -> google.protobuf.MessageOptions
	0,  // 9: eventapi.v1.event_data_content_type:type_name -> eventapi.v1.EventDataContentType
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	9,  // [9:10] is the sub-list for extension type_name
	5,  // [5:9] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_eventapi_v1_cloudevent_proto_init() }
func file_eventapi_v1_cloudevent_proto_init() {
	if File_eventapi_v1_cloudevent_proto != nil {
		return
	}
	file_eventapi_v1_cloudevent_proto_msgTypes[2].OneofWrappers = []any{
		(*CloudEvent_AttributeValue_Boolean)(nil),
		(*CloudEvent_AttributeValue_Integer)(nil),
		(*CloudEvent_AttributeValue_String_)(nil),
		(*CloudEvent_AttributeValue_Bytes)(nil),
		(*CloudEvent_AttributeValue_Uri)(nil),
		(*CloudEvent_AttributeValue_UriRef)(nil),
		(*CloudEvent_AttributeValue_Timestamp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eventapi_v1_cloudevent_proto_rawDesc), len(file_eventapi_v1_cloudevent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_eventapi_v1_cloudevent_proto_goTypes,
		DependencyIndexes: file_eventapi_v1_cloudevent_proto_depIdxs,
		EnumInfos:         file_eventapi_v1_cloudevent_proto_enumTypes,
		MessageInfos:      file_eventapi_v1_cloudevent_proto_msgTypes,
		ExtensionInfos:    file_eventapi_v1_cloudevent_proto_extTypes,
	}.Build()
	File_eventapi_v1_cloudevent_proto = out.File
	file_eventapi_v1_cloudevent_proto_goTypes = nil
	file_eventapi_v1_cloudevent_proto_depIdxs = nil
}
