// EventAPI Core IDL
//
// EventAPI 是一个基于 Protobuf 的异步事件驱动架构规范，它将 CloudEvents 的事件模型
// 与 AsyncAPI 的拓扑架构完美融合，提供类型安全、自描述的异步通信能力。
//
// 设计参考:
// - CloudEvents Spec: https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md
// - CloudEvents Protobuf Format: https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/formats/protobuf-format.md
// - AsyncAPI Spec: https://www.asyncapi.com/docs/reference/specification/latest
//
// =====================================================================
// 使用方法
// =====================================================================
//
// 1. 定义 Service，声明传输协议:
//
//    service UserEventBus {
//      option (eventapi.v1.server) = {
//        protocols: [
//          { name: "kafka", version: "3.5.0" }
//        ]
//      };
//      ...
//    }
//
// 2. 定义 RPC 方法，声明通道拓扑:
//
//    rpc SendUserCreated(UserCreatedEvent) returns (google.protobuf.Empty) {
//      option (eventapi.v1.operation) = {
//        action: SEND
//        channel: {
//          address: "user.events"
//          description: "用户事件通道"
//        }
//      };
//    }
//
// 3. 定义 Message，声明事件类型和 subject 字段:
//
//    message UserCreatedEvent {
//      option (eventapi.v1.event_type) = "acme.user.created.v1";
//      string user_id = 1 [(eventapi.v1.is_event_subject) = true];
//      string email = 2;
//      int64 created_at = 3;
//    }
//
// 4. 生成代码:
//
//    protoc \
//      --plugin=protoc-gen-eventapi=./protoc-gen-eventapi \
//      --eventapi_out=. \
//      --go_out=. \
//      --proto_path=. \
//      your_service.proto
//
// =====================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: eventapi/v1/eventapi.proto

package eventapiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 操作动作枚举
type OperationRule_ActionType int32

const (
	OperationRule_UNSPECIFIED OperationRule_ActionType = 0
	OperationRule_SEND        OperationRule_ActionType = 1
	OperationRule_RECEIVE     OperationRule_ActionType = 2
)

// Enum value maps for OperationRule_ActionType.
var (
	OperationRule_ActionType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "SEND",
		2: "RECEIVE",
	}
	OperationRule_ActionType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"SEND":        1,
		"RECEIVE":     2,
	}
)

func (x OperationRule_ActionType) Enum() *OperationRule_ActionType {
	p := new(OperationRule_ActionType)
	*p = x
	return p
}

func (x OperationRule_ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationRule_ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_eventapi_v1_eventapi_proto_enumTypes[0].Descriptor()
}

func (OperationRule_ActionType) Type() protoreflect.EnumType {
	return &file_eventapi_v1_eventapi_proto_enumTypes[0]
}

func (x OperationRule_ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationRule_ActionType.Descriptor instead.
func (OperationRule_ActionType) EnumDescriptor() ([]byte, []int) {
	return file_eventapi_v1_eventapi_proto_rawDescGZIP(), []int{2, 0}
}

// 消息类型枚举
type OperationRule_Channel_Binding_Rocketmq_MessageType int32

const (
	// 普通消息
	OperationRule_Channel_Binding_Rocketmq_NORMAL OperationRule_Channel_Binding_Rocketmq_MessageType = 0
	// 顺序消息（分区有序）
	OperationRule_Channel_Binding_Rocketmq_ORDER OperationRule_Channel_Binding_Rocketmq_MessageType = 1
	// 事务消息
	OperationRule_Channel_Binding_Rocketmq_TRANSACTION OperationRule_Channel_Binding_Rocketmq_MessageType = 2
	// 延时消息
	OperationRule_Channel_Binding_Rocketmq_DELAY OperationRule_Channel_Binding_Rocketmq_MessageType = 3
)

// Enum value maps for OperationRule_Channel_Binding_Rocketmq_MessageType.
var (
	OperationRule_Channel_Binding_Rocketmq_MessageType_name = map[int32]string{
		0: "NORMAL",
		1: "ORDER",
		2: "TRANSACTION",
		3: "DELAY",
	}
	OperationRule_Channel_Binding_Rocketmq_MessageType_value = map[string]int32{
		"NORMAL":      0,
		"ORDER":       1,
		"TRANSACTION": 2,
		"DELAY":       3,
	}
)

func (x OperationRule_Channel_Binding_Rocketmq_MessageType) Enum() *OperationRule_Channel_Binding_Rocketmq_MessageType {
	p := new(OperationRule_Channel_Binding_Rocketmq_MessageType)
	*p = x
	return p
}

func (x OperationRule_Channel_Binding_Rocketmq_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationRule_Channel_Binding_Rocketmq_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_eventapi_v1_eventapi_proto_enumTypes[1].Descriptor()
}

func (OperationRule_Channel_Binding_Rocketmq_MessageType) Type() protoreflect.EnumType {
	return &file_eventapi_v1_eventapi_proto_enumTypes[1]
}

func (x OperationRule_Channel_Binding_Rocketmq_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationRule_Channel_Binding_Rocketmq_MessageType.Descriptor instead.
func (OperationRule_Channel_Binding_Rocketmq_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_eventapi_v1_eventapi_proto_rawDescGZIP(), []int{2, 0, 0, 4, 0}
}

// Service 级别：AsyncAPI Server（Broker）协议配置
// 对应 AsyncAPI 规范中的 Server Object
// 参考: https://www.asyncapi.com/docs/reference/specification/latest#serverObject
type AsyncApiServerRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 支持的协议列表
	// 当有多个协议时，会为每个协议生成一个独立的 SDK
	// 例如: [{name: "kafka", version: "3.5.0"}, {name: "amqp", version: "0.9.1"}]
	Protocols     []*Protocol `protobuf:"bytes,1,rep,name=protocols,proto3" json:"protocols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncApiServerRule) Reset() {
	*x = AsyncApiServerRule{}
	mi := &file_eventapi_v1_eventapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncApiServerRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncApiServerRule) ProtoMessage() {}

func (x *AsyncApiServerRule) ProtoReflect() protoreflect.Message {
	mi := &file_eventapi_v1_eventapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncApiServerRule.ProtoReflect.Descriptor instead.
func (*AsyncApiServerRule) Descriptor() ([]byte, []int) {
	return file_eventapi_v1_eventapi_proto_rawDescGZIP(), []int{0}
}

func (x *AsyncApiServerRule) GetProtocols() []*Protocol {
	if x != nil {
		return x.Protocols
	}
	return nil
}

// 协议定义
type Protocol struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 协议名称，如: kafka, amqp, mqtt, nats, rocketmq
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 协议版本，如: "3.5.0" (Kafka), "0.9.1" (AMQP)
	Version       string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Protocol) Reset() {
	*x = Protocol{}
	mi := &file_eventapi_v1_eventapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Protocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Protocol) ProtoMessage() {}

func (x *Protocol) ProtoReflect() protoreflect.Message {
	mi := &file_eventapi_v1_eventapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Protocol.ProtoReflect.Descriptor instead.
func (*Protocol) Descriptor() ([]byte, []int) {
	return file_eventapi_v1_eventapi_proto_rawDescGZIP(), []int{1}
}

func (x *Protocol) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Protocol) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Method 级别：通道与操作配置
// 对应 Channel Item Object
type OperationRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 操作动作: send 或 receive
	Action OperationRule_ActionType `protobuf:"varint,1,opt,name=action,proto3,enum=eventapi.v1.OperationRule_ActionType" json:"action,omitempty"`
	// 通道配置，包含地址、描述和协议绑定
	Channel       *OperationRule_Channel `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRule) Reset() {
	*x = OperationRule{}
	mi := &file_eventapi_v1_eventapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRule) ProtoMessage() {}

func (x *OperationRule) ProtoReflect() protoreflect.Message {
	mi := &file_eventapi_v1_eventapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRule.ProtoReflect.Descriptor instead.
func (*OperationRule) Descriptor() ([]byte, []int) {
	return file_eventapi_v1_eventapi_proto_rawDescGZIP(), []int{2}
}

func (x *OperationRule) GetAction() OperationRule_ActionType {
	if x != nil {
		return x.Action
	}
	return OperationRule_UNSPECIFIED
}

func (x *OperationRule) GetChannel() *OperationRule_Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

// Channel 通道定义
// 参考: https://www.asyncapi.com/docs/reference/specification/latest#channelItemObject
type OperationRule_Channel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 通道地址，即 Topic 或 Queue 名称
	// 例如: "user.events", "order.created"
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// 通道描述，用于文档生成
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// 协议特定的绑定配置
	// 参考: https://github.com/asyncapi/bindings
	Binding       *OperationRule_Channel_Binding `protobuf:"bytes,3,opt,name=binding,proto3" json:"binding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRule_Channel) Reset() {
	*x = OperationRule_Channel{}
	mi := &file_eventapi_v1_eventapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRule_Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRule_Channel) ProtoMessage() {}

func (x *OperationRule_Channel) ProtoReflect() protoreflect.Message {
	mi := &file_eventapi_v1_eventapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRule_Channel.ProtoReflect.Descriptor instead.
func (*OperationRule_Channel) Descriptor() ([]byte, []int) {
	return file_eventapi_v1_eventapi_proto_rawDescGZIP(), []int{2, 0}
}

func (x *OperationRule_Channel) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OperationRule_Channel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OperationRule_Channel) GetBinding() *OperationRule_Channel_Binding {
	if x != nil {
		return x.Binding
	}
	return nil
}

// 协议绑定配置
// 包含 Kafka, AMQP, MQTT 等协议的特定配置
type OperationRule_Channel_Binding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kafka 协议绑定
	// 参考: https://github.com/asyncapi/bindings/tree/master/kafka
	Kafka *OperationRule_Channel_Binding_Kafka `protobuf:"bytes,1,opt,name=kafka,proto3" json:"kafka,omitempty"`
	// AMQP 协议绑定
	// 参考: https://github.com/asyncapi/bindings/tree/master/amqp
	Amqp *OperationRule_Channel_Binding_Amqp `protobuf:"bytes,2,opt,name=amqp,proto3" json:"amqp,omitempty"`
	// MQTT 协议绑定
	// 参考: https://github.com/asyncapi/bindings/tree/master/mqtt
	Mqtt *OperationRule_Channel_Binding_Mqtt `protobuf:"bytes,3,opt,name=mqtt,proto3" json:"mqtt,omitempty"`
	// NATS 协议绑定
	// 参考: https://github.com/asyncapi/bindings/tree/master/nats
	Nats *OperationRule_Channel_Binding_Nats `protobuf:"bytes,4,opt,name=nats,proto3" json:"nats,omitempty"`
	// RocketMQ 协议绑定
	// 参考: https://github.com/asyncapi/bindings/tree/master/rocketmq
	Rocketmq      *OperationRule_Channel_Binding_Rocketmq `protobuf:"bytes,5,opt,name=rocketmq,proto3" json:"rocketmq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRule_Channel_Binding) Reset() {
	*x = OperationRule_Channel_Binding{}
	mi := &file_eventapi_v1_eventapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRule_Channel_Binding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRule_Channel_Binding) ProtoMessage() {}

func (x *OperationRule_Channel_Binding) ProtoReflect() protoreflect.Message {
	mi := &file_eventapi_v1_eventapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRule_Channel_Binding.ProtoReflect.Descriptor instead.
func (*OperationRule_Channel_Binding) Descriptor() ([]byte, []int) {
	return file_eventapi_v1_eventapi_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *OperationRule_Channel_Binding) GetKafka() *OperationRule_Channel_Binding_Kafka {
	if x != nil {
		return x.Kafka
	}
	return nil
}

func (x *OperationRule_Channel_Binding) GetAmqp() *OperationRule_Channel_Binding_Amqp {
	if x != nil {
		return x.Amqp
	}
	return nil
}

func (x *OperationRule_Channel_Binding) GetMqtt() *OperationRule_Channel_Binding_Mqtt {
	if x != nil {
		return x.Mqtt
	}
	return nil
}

func (x *OperationRule_Channel_Binding) GetNats() *OperationRule_Channel_Binding_Nats {
	if x != nil {
		return x.Nats
	}
	return nil
}

func (x *OperationRule_Channel_Binding) GetRocketmq() *OperationRule_Channel_Binding_Rocketmq {
	if x != nil {
		return x.Rocketmq
	}
	return nil
}

// Kafka 绑定配置
type OperationRule_Channel_Binding_Kafka struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息 Key，用于分区路由
	// 例如: "user_id" 表示按用户 ID 路由到不同分区
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// 指定分区号 (可选)
	// 如果不指定，使用默认分区策略
	Partition     int32 `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRule_Channel_Binding_Kafka) Reset() {
	*x = OperationRule_Channel_Binding_Kafka{}
	mi := &file_eventapi_v1_eventapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRule_Channel_Binding_Kafka) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRule_Channel_Binding_Kafka) ProtoMessage() {}

func (x *OperationRule_Channel_Binding_Kafka) ProtoReflect() protoreflect.Message {
	mi := &file_eventapi_v1_eventapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRule_Channel_Binding_Kafka.ProtoReflect.Descriptor instead.
func (*OperationRule_Channel_Binding_Kafka) Descriptor() ([]byte, []int) {
	return file_eventapi_v1_eventapi_proto_rawDescGZIP(), []int{2, 0, 0, 0}
}

func (x *OperationRule_Channel_Binding_Kafka) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OperationRule_Channel_Binding_Kafka) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

// AMQP 绑定配置
type OperationRule_Channel_Binding_Amqp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exchange 名称
	// 参考: https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchanges
	Exchange string `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// Routing Key 模式
	// 参考: https://www.rabbitmq.com/tutorials/amqp-concepts.html#bindings
	RoutingKey    string `protobuf:"bytes,2,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRule_Channel_Binding_Amqp) Reset() {
	*x = OperationRule_Channel_Binding_Amqp{}
	mi := &file_eventapi_v1_eventapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRule_Channel_Binding_Amqp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRule_Channel_Binding_Amqp) ProtoMessage() {}

func (x *OperationRule_Channel_Binding_Amqp) ProtoReflect() protoreflect.Message {
	mi := &file_eventapi_v1_eventapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRule_Channel_Binding_Amqp.ProtoReflect.Descriptor instead.
func (*OperationRule_Channel_Binding_Amqp) Descriptor() ([]byte, []int) {
	return file_eventapi_v1_eventapi_proto_rawDescGZIP(), []int{2, 0, 0, 1}
}

func (x *OperationRule_Channel_Binding_Amqp) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *OperationRule_Channel_Binding_Amqp) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

// MQTT 绑定配置
type OperationRule_Channel_Binding_Mqtt struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// QoS 等级 (0, 1, 2)
	// 0: 最多一次 (At most once)
	// 1: 至少一次 (At least once)
	// 2: 恰好一次 (Exactly once)
	// 参考: https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901234
	Qos int32 `protobuf:"varint,1,opt,name=qos,proto3" json:"qos,omitempty"`
	// 是否保留消息
	// true: Broker 会保留最后一条消息，新订阅者立即收到
	// false: 普通消息，不保留
	Retain        bool `protobuf:"varint,2,opt,name=retain,proto3" json:"retain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRule_Channel_Binding_Mqtt) Reset() {
	*x = OperationRule_Channel_Binding_Mqtt{}
	mi := &file_eventapi_v1_eventapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRule_Channel_Binding_Mqtt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRule_Channel_Binding_Mqtt) ProtoMessage() {}

func (x *OperationRule_Channel_Binding_Mqtt) ProtoReflect() protoreflect.Message {
	mi := &file_eventapi_v1_eventapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRule_Channel_Binding_Mqtt.ProtoReflect.Descriptor instead.
func (*OperationRule_Channel_Binding_Mqtt) Descriptor() ([]byte, []int) {
	return file_eventapi_v1_eventapi_proto_rawDescGZIP(), []int{2, 0, 0, 2}
}

func (x *OperationRule_Channel_Binding_Mqtt) GetQos() int32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

func (x *OperationRule_Channel_Binding_Mqtt) GetRetain() bool {
	if x != nil {
		return x.Retain
	}
	return false
}

// NATS 绑定配置 (占位)
type OperationRule_Channel_Binding_Nats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRule_Channel_Binding_Nats) Reset() {
	*x = OperationRule_Channel_Binding_Nats{}
	mi := &file_eventapi_v1_eventapi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRule_Channel_Binding_Nats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRule_Channel_Binding_Nats) ProtoMessage() {}

func (x *OperationRule_Channel_Binding_Nats) ProtoReflect() protoreflect.Message {
	mi := &file_eventapi_v1_eventapi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRule_Channel_Binding_Nats.ProtoReflect.Descriptor instead.
func (*OperationRule_Channel_Binding_Nats) Descriptor() ([]byte, []int) {
	return file_eventapi_v1_eventapi_proto_rawDescGZIP(), []int{2, 0, 0, 3}
}

// RocketMQ 绑定配置
// 支持阿里云 RocketMQ 和开源 RocketMQ
type OperationRule_Channel_Binding_Rocketmq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息 Tag，用于消息过滤
	// 例如: "ORDER_STATUS_CHANGE"
	Tag string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	// 消息 Key，用于消息查询和去重
	// 例如: 订单ID、用户ID
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// 消息类型
	MessageType OperationRule_Channel_Binding_Rocketmq_MessageType `protobuf:"varint,3,opt,name=message_type,json=messageType,proto3,enum=eventapi.v1.OperationRule_Channel_Binding_Rocketmq_MessageType" json:"message_type,omitempty"`
	// 延时消息级别（仅当 message_type = DELAY 时有效）
	// 阿里云 RocketMQ 延时级别：
	// 1s 5s 10s 30s 1m 2m 3m 4m 5m 6m 7m 8m 9m 10m 20m 30m 1h 2h
	DelayLevel    int32 `protobuf:"varint,4,opt,name=delay_level,json=delayLevel,proto3" json:"delay_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRule_Channel_Binding_Rocketmq) Reset() {
	*x = OperationRule_Channel_Binding_Rocketmq{}
	mi := &file_eventapi_v1_eventapi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRule_Channel_Binding_Rocketmq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRule_Channel_Binding_Rocketmq) ProtoMessage() {}

func (x *OperationRule_Channel_Binding_Rocketmq) ProtoReflect() protoreflect.Message {
	mi := &file_eventapi_v1_eventapi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRule_Channel_Binding_Rocketmq.ProtoReflect.Descriptor instead.
func (*OperationRule_Channel_Binding_Rocketmq) Descriptor() ([]byte, []int) {
	return file_eventapi_v1_eventapi_proto_rawDescGZIP(), []int{2, 0, 0, 4}
}

func (x *OperationRule_Channel_Binding_Rocketmq) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *OperationRule_Channel_Binding_Rocketmq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OperationRule_Channel_Binding_Rocketmq) GetMessageType() OperationRule_Channel_Binding_Rocketmq_MessageType {
	if x != nil {
		return x.MessageType
	}
	return OperationRule_Channel_Binding_Rocketmq_NORMAL
}

func (x *OperationRule_Channel_Binding_Rocketmq) GetDelayLevel() int32 {
	if x != nil {
		return x.DelayLevel
	}
	return 0
}

var file_eventapi_v1_eventapi_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*AsyncApiServerRule)(nil),
		Field:         50201,
		Name:          "eventapi.v1.server",
		Tag:           "bytes,50201,opt,name=server",
		Filename:      "eventapi/v1/eventapi.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*OperationRule)(nil),
		Field:         50101,
		Name:          "eventapi.v1.operation",
		Tag:           "bytes,50101,opt,name=operation",
		Filename:      "eventapi/v1/eventapi.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// server 选项编号: 50201
	// 用于配置 AsyncAPI Server (即消息 Broker) 的协议信息
	//
	// optional eventapi.v1.AsyncApiServerRule server = 50201;
	E_Server = &file_eventapi_v1_eventapi_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// operation 选项编号: 50101
	// 用于配置 Channel (即 Topic/Queue) 和操作类型
	//
	// optional eventapi.v1.OperationRule operation = 50101;
	E_Operation = &file_eventapi_v1_eventapi_proto_extTypes[1]
)

var File_eventapi_v1_eventapi_proto protoreflect.FileDescriptor

const file_eventapi_v1_eventapi_proto_rawDesc = "" +
	"\n" +
	"\x1aeventapi/v1/eventapi.proto\x12\veventapi.v1\x1a\x1ceventapi/v1/cloudevent.proto\x1a google/protobuf/descriptor.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"I\n" +
	"\x12AsyncApiServerRule\x123\n" +
	"\tprotocols\x18\x01 \x03(\v2\x15.eventapi.v1.ProtocolR\tprotocols\"8\n" +
	"\bProtocol\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xf4\b\n" +
	"\rOperationRule\x12=\n" +
	"\x06action\x18\x01 \x01(\x0e2%.eventapi.v1.OperationRule.ActionTypeR\x06action\x12<\n" +
	"\achannel\x18\x02 \x01(\v2\".eventapi.v1.OperationRule.ChannelR\achannel\x1a\xaf\a\n" +
	"\aChannel\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12D\n" +
	"\abinding\x18\x03 \x01(\v2*.eventapi.v1.OperationRule.Channel.BindingR\abinding\x1a\xa1\x06\n" +
	"\aBinding\x12F\n" +
	"\x05kafka\x18\x01 \x01(\v20.eventapi.v1.OperationRule.Channel.Binding.KafkaR\x05kafka\x12C\n" +
	"\x04amqp\x18\x02 \x01(\v2/.eventapi.v1.OperationRule.Channel.Binding.AmqpR\x04amqp\x12C\n" +
	"\x04mqtt\x18\x03 \x01(\v2/.eventapi.v1.OperationRule.Channel.Binding.MqttR\x04mqtt\x12C\n" +
	"\x04nats\x18\x04 \x01(\v2/.eventapi.v1.OperationRule.Channel.Binding.NatsR\x04nats\x12O\n" +
	"\brocketmq\x18\x05 \x01(\v23.eventapi.v1.OperationRule.Channel.Binding.RocketmqR\brocketmq\x1a7\n" +
	"\x05Kafka\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\x1aC\n" +
	"\x04Amqp\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x1f\n" +
	"\vrouting_key\x18\x02 \x01(\tR\n" +
	"routingKey\x1a0\n" +
	"\x04Mqtt\x12\x10\n" +
	"\x03qos\x18\x01 \x01(\x05R\x03qos\x12\x16\n" +
	"\x06retain\x18\x02 \x01(\bR\x06retain\x1a\x06\n" +
	"\x04Nats\x1a\xf5\x01\n" +
	"\bRocketmq\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12b\n" +
	"\fmessage_type\x18\x03 \x01(\x0e2?.eventapi.v1.OperationRule.Channel.Binding.Rocketmq.MessageTypeR\vmessageType\x12\x1f\n" +
	"\vdelay_level\x18\x04 \x01(\x05R\n" +
	"delayLevel\"@\n" +
	"\vMessageType\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x00\x12\t\n" +
	"\x05ORDER\x10\x01\x12\x0f\n" +
	"\vTRANSACTION\x10\x02\x12\t\n" +
	"\x05DELAY\x10\x03\"4\n" +
	"\n" +
	"ActionType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\b\n" +
	"\x04SEND\x10\x01\x12\v\n" +
	"\aRECEIVE\x10\x02:Z\n" +
	"\x06server\x12\x1f.google.protobuf.ServiceOptions\x18\x99\x88\x03 \x01(\v2\x1f.eventapi.v1.AsyncApiServerRuleR\x06server:Z\n" +
	"\toperation\x12\x1e.google.protobuf.MethodOptions\x18\xb5\x87\x03 \x01(\v2\x1a.eventapi.v1.OperationRuleR\toperationB\xa9\x01\n" +
	"\x0fcom.eventapi.v1B\rEventapiProtoP\x01Z:github.com/eventapi/eventapi-go/pkg/eventapi/v1;eventapiv1\xa2\x02\x03EXX\xaa\x02\vEventapi.V1\xca\x02\vEventapi\\V1\xe2\x02\x17Eventapi\\V1\\GPBMetadata\xea\x02\fEventapi::V1b\x06proto3"

var (
	file_eventapi_v1_eventapi_proto_rawDescOnce sync.Once
	file_eventapi_v1_eventapi_proto_rawDescData []byte
)

func file_eventapi_v1_eventapi_proto_rawDescGZIP() []byte {
	file_eventapi_v1_eventapi_proto_rawDescOnce.Do(func() {
		file_eventapi_v1_eventapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eventapi_v1_eventapi_proto_rawDesc), len(file_eventapi_v1_eventapi_proto_rawDesc)))
	})
	return file_eventapi_v1_eventapi_proto_rawDescData
}

var file_eventapi_v1_eventapi_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_eventapi_v1_eventapi_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_eventapi_v1_eventapi_proto_goTypes = []any{
	(OperationRule_ActionType)(0),                           // 0: eventapi.v1.OperationRule.ActionType
	(OperationRule_Channel_Binding_Rocketmq_MessageType)(0), // 1: eventapi.v1.OperationRule.Channel.Binding.Rocketmq.MessageType
	(*AsyncApiServerRule)(nil),                              // 2: eventapi.v1.AsyncApiServerRule
	(*Protocol)(nil),                                        // 3: eventapi.v1.Protocol
	(*OperationRule)(nil),                                   // 4: eventapi.v1.OperationRule
	(*OperationRule_Channel)(nil),                           // 5: eventapi.v1.OperationRule.Channel
	(*OperationRule_Channel_Binding)(nil),                   // 6: eventapi.v1.OperationRule.Channel.Binding
	(*OperationRule_Channel_Binding_Kafka)(nil),             // 7: eventapi.v1.OperationRule.Channel.Binding.Kafka
	(*OperationRule_Channel_Binding_Amqp)(nil),              // 8: eventapi.v1.OperationRule.Channel.Binding.Amqp
	(*OperationRule_Channel_Binding_Mqtt)(nil),              // 9: eventapi.v1.OperationRule.Channel.Binding.Mqtt
	(*OperationRule_Channel_Binding_Nats)(nil),              // 10: eventapi.v1.OperationRule.Channel.Binding.Nats
	(*OperationRule_Channel_Binding_Rocketmq)(nil),          // 11: eventapi.v1.OperationRule.Channel.Binding.Rocketmq
	(*descriptorpb.ServiceOptions)(nil),                     // 12: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),                      // 13: google.protobuf.MethodOptions
}
var file_eventapi_v1_eventapi_proto_depIdxs = []int32{
	3,  // 0: eventapi.v1.AsyncApiServerRule.protocols:type_name -> eventapi.v1.Protocol
	0,  // 1: eventapi.v1.OperationRule.action:type_name -> eventapi.v1.OperationRule.ActionType
	5,  // 2: eventapi.v1.OperationRule.channel:type_name -> eventapi.v1.OperationRule.Channel
	6,  // 3: eventapi.v1.OperationRule.Channel.binding:type_name -> eventapi.v1.OperationRule.Channel.Binding
	7,  // 4: eventapi.v1.OperationRule.Channel.Binding.kafka:type_name -> eventapi.v1.OperationRule.Channel.Binding.Kafka
	8,  // 5: eventapi.v1.OperationRule.Channel.Binding.amqp:type_name -> eventapi.v1.OperationRule.Channel.Binding.Amqp
	9,  // 6: eventapi.v1.OperationRule.Channel.Binding.mqtt:type_name -> eventapi.v1.OperationRule.Channel.Binding.Mqtt
	10, // 7: eventapi.v1.OperationRule.Channel.Binding.nats:type_name -> eventapi.v1.OperationRule.Channel.Binding.Nats
	11, // 8: eventapi.v1.OperationRule.Channel.Binding.rocketmq:type_name -> eventapi.v1.OperationRule.Channel.Binding.Rocketmq
	1,  // 9: eventapi.v1.OperationRule.Channel.Binding.Rocketmq.message_type:type_name -> eventapi.v1.OperationRule.Channel.Binding.Rocketmq.MessageType
	12, // 10: eventapi.v1.server:extendee -> google.protobuf.ServiceOptions
	13, // 11: eventapi.v1.operation:extendee -> google.protobuf.MethodOptions
	2,  // 12: eventapi.v1.server:type_name -> eventapi.v1.AsyncApiServerRule
	4,  // 13: eventapi.v1.operation:type_name -> eventapi.v1.OperationRule
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	12, // [12:14] is the sub-list for extension type_name
	10, // [10:12] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_eventapi_v1_eventapi_proto_init() }
func file_eventapi_v1_eventapi_proto_init() {
	if File_eventapi_v1_eventapi_proto != nil {
		return
	}
	file_eventapi_v1_cloudevent_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eventapi_v1_eventapi_proto_rawDesc), len(file_eventapi_v1_eventapi_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_eventapi_v1_eventapi_proto_goTypes,
		DependencyIndexes: file_eventapi_v1_eventapi_proto_depIdxs,
		EnumInfos:         file_eventapi_v1_eventapi_proto_enumTypes,
		MessageInfos:      file_eventapi_v1_eventapi_proto_msgTypes,
		ExtensionInfos:    file_eventapi_v1_eventapi_proto_extTypes,
	}.Build()
	File_eventapi_v1_eventapi_proto = out.File
	file_eventapi_v1_eventapi_proto_goTypes = nil
	file_eventapi_v1_eventapi_proto_depIdxs = nil
}
