// EventAPI Sink IDL
//
// 定义事件与下游数据接收端（StarRocks、MySQL 等）的字段映射，
// 用于自动生成 DDL 建表语句和 Flink SQL pipeline。
//
// =====================================================================
// 惯例
// =====================================================================
//
// sink 与 operation 写在同一个 SEND rpc 上：
//
//   rpc SendOrder(OrderEvent) returns (google.protobuf.Empty) {
//     option (eventapi.v1.operation) = { ... };  // 怎么发
//     option (eventapi.v1.sink) = { ... };        // 发完去哪
//   }
//
// 规则：
//   - sink 只放在 action: SEND 的 rpc 上
//   - RECEIVE rpc 不写 sink
//   - 一个 rpc 可配多个 sink（同一消息落多个目标）
//
// =====================================================================
// 完整示例
// =====================================================================
//
//   rpc SendOrder(OrderEvent) returns (google.protobuf.Empty) {
//     option (eventapi.v1.operation) = {
//       action: SEND
//       channel: { address: "order.events" }
//     };
//     option (eventapi.v1.sink) = {
//       target: SINK_TYPE_STARROCKS
//       database: "analytics"
//       table: "order_events"
//       source_topic: "order.events"
//       event_data_content_type: CONTENT_TYPE_JSON
//       primary_key: ["event_id"]
//       partition_key: ["event_time"]
//       mapping: [
//         // CloudEvent header 字段
//         { header_path: "ce_id",      target_column: "event_id",   type: COLUMN_TYPE_VARCHAR, not_null: true },
//         { header_path: "ce_type",    target_column: "event_type", type: COLUMN_TYPE_VARCHAR },
//         { header_path: "ce_source",  target_column: "event_source", type: COLUMN_TYPE_VARCHAR },
//         { header_path: "ce_time",    target_column: "event_time", type: COLUMN_TYPE_TIMESTAMP },
//         { header_path: "ce_subject", target_column: "subject",    type: COLUMN_TYPE_VARCHAR },
//
//         // 消息体 data 字段（JSON 路径）
//         { data_path: "$.order_id",     target_column: "order_id",    type: COLUMN_TYPE_VARCHAR, not_null: true },
//         { data_path: "$.user_id",      target_column: "user_id",     type: COLUMN_TYPE_VARCHAR },
//         { data_path: "$.order_amount", target_column: "order_amount",type: COLUMN_TYPE_BIGINT },
//         { data_path: "$.order_status", target_column: "order_status",type: COLUMN_TYPE_VARCHAR },
//
//         // 嵌套提取：header 值是 JSON 时
//         { header_path: "$.ce_source.tenant", target_column: "tenant_id", type: COLUMN_TYPE_VARCHAR }
//       ]
//     };
//   }
//
// =====================================================================
// 字段映射规则
// =====================================================================
//
// header_path:
//   - 直接读取: "ce_id", "ce_type", "ce_source", "ce_time", "ce_subject"
//   - 嵌套提取: "$.ce_source.tenant" → JSON_VALUE(ce_source, '$.tenant')
//
// data_path:
//   - CONTENT_TYPE_JSON:  Flink 自动反序列化，直接映射列
//   - 其他格式:           JSON_VALUE(value, '$.field') 手动解析
//
// =====================================================================
// 自动推断
// =====================================================================
//
// 生成器会自动遍历 RPC 入参 Message 的所有字段，
// 对于未在 mapping 中显式声明 data_path 的字段，按以下规则自动补全：
//
//   1. data_path:      $.<field_name>
//   2. target_column:  <field_name> (保持 snake_case)
//   3. type:           根据 Proto 字段类型自动转换（见下表）
//   4. not_null:       optional 为 false，否则 true
//   5. comment:        自动提取 Proto 字段注释
//
// Proto 类型 → Sink 类型:
//   string                      → VARCHAR
//   int32/int64/uint32/uint64   → BIGINT
//   bool                        → BOOLEAN
//   float/double                → DOUBLE
//   google.protobuf.Timestamp   → TIMESTAMP
//   google.protobuf.Struct/map  → JSON
//   bytes                       → VARCHAR (Base64)
//   enum                        → VARCHAR
//
// 关闭自动推断:
//   option (eventapi.v1.sink) = {
//     auto_infer_data_mapping: false
//     mapping: [ ... ]  // 必须手动写全所有字段
//   };
//
// =====================================================================
// 生成
// =====================================================================
//
//   buf generate --template buf.gen.sink.yaml
//
// 产物：DDL 建表语句 + Flink SQL pipeline
//
// =====================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: eventapi/v1/sink.proto

package eventapiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SinkType int32

const (
	SinkType_SINK_TYPE_UNSPECIFIED SinkType = 0
	SinkType_SINK_TYPE_STARROCKS   SinkType = 1
	SinkType_SINK_TYPE_MYSQL       SinkType = 2
	SinkType_SINK_TYPE_CLICKHOUSE  SinkType = 3
	SinkType_SINK_TYPE_POSTGRESQL  SinkType = 4
)

// Enum value maps for SinkType.
var (
	SinkType_name = map[int32]string{
		0: "SINK_TYPE_UNSPECIFIED",
		1: "SINK_TYPE_STARROCKS",
		2: "SINK_TYPE_MYSQL",
		3: "SINK_TYPE_CLICKHOUSE",
		4: "SINK_TYPE_POSTGRESQL",
	}
	SinkType_value = map[string]int32{
		"SINK_TYPE_UNSPECIFIED": 0,
		"SINK_TYPE_STARROCKS":   1,
		"SINK_TYPE_MYSQL":       2,
		"SINK_TYPE_CLICKHOUSE":  3,
		"SINK_TYPE_POSTGRESQL":  4,
	}
)

func (x SinkType) Enum() *SinkType {
	p := new(SinkType)
	*p = x
	return p
}

func (x SinkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SinkType) Descriptor() protoreflect.EnumDescriptor {
	return file_eventapi_v1_sink_proto_enumTypes[0].Descriptor()
}

func (SinkType) Type() protoreflect.EnumType {
	return &file_eventapi_v1_sink_proto_enumTypes[0]
}

func (x SinkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SinkType.Descriptor instead.
func (SinkType) EnumDescriptor() ([]byte, []int) {
	return file_eventapi_v1_sink_proto_rawDescGZIP(), []int{0}
}

type ColumnType int32

const (
	ColumnType_COLUMN_TYPE_UNSPECIFIED ColumnType = 0
	ColumnType_COLUMN_TYPE_VARCHAR     ColumnType = 1
	ColumnType_COLUMN_TYPE_BIGINT      ColumnType = 2
	ColumnType_COLUMN_TYPE_TIMESTAMP   ColumnType = 3
	ColumnType_COLUMN_TYPE_DECIMAL     ColumnType = 4
	ColumnType_COLUMN_TYPE_BOOLEAN     ColumnType = 5
	ColumnType_COLUMN_TYPE_JSON        ColumnType = 6
	ColumnType_COLUMN_TYPE_DOUBLE      ColumnType = 7
)

// Enum value maps for ColumnType.
var (
	ColumnType_name = map[int32]string{
		0: "COLUMN_TYPE_UNSPECIFIED",
		1: "COLUMN_TYPE_VARCHAR",
		2: "COLUMN_TYPE_BIGINT",
		3: "COLUMN_TYPE_TIMESTAMP",
		4: "COLUMN_TYPE_DECIMAL",
		5: "COLUMN_TYPE_BOOLEAN",
		6: "COLUMN_TYPE_JSON",
		7: "COLUMN_TYPE_DOUBLE",
	}
	ColumnType_value = map[string]int32{
		"COLUMN_TYPE_UNSPECIFIED": 0,
		"COLUMN_TYPE_VARCHAR":     1,
		"COLUMN_TYPE_BIGINT":      2,
		"COLUMN_TYPE_TIMESTAMP":   3,
		"COLUMN_TYPE_DECIMAL":     4,
		"COLUMN_TYPE_BOOLEAN":     5,
		"COLUMN_TYPE_JSON":        6,
		"COLUMN_TYPE_DOUBLE":      7,
	}
)

func (x ColumnType) Enum() *ColumnType {
	p := new(ColumnType)
	*p = x
	return p
}

func (x ColumnType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColumnType) Descriptor() protoreflect.EnumDescriptor {
	return file_eventapi_v1_sink_proto_enumTypes[1].Descriptor()
}

func (ColumnType) Type() protoreflect.EnumType {
	return &file_eventapi_v1_sink_proto_enumTypes[1]
}

func (x ColumnType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColumnType.Descriptor instead.
func (ColumnType) EnumDescriptor() ([]byte, []int) {
	return file_eventapi_v1_sink_proto_rawDescGZIP(), []int{1}
}

// Method 级别：Sink 目标配置
type SinkRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 目标系统类型
	Target SinkType `protobuf:"varint,1,opt,name=target,proto3,enum=eventapi.v1.SinkType" json:"target,omitempty"`
	// 目标数据库名
	Database string `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	// 目标表名
	Table string `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	// 主键列
	PrimaryKey []string `protobuf:"bytes,4,rep,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	// 分区列
	PartitionKey []string `protobuf:"bytes,5,rep,name=partition_key,json=partitionKey,proto3" json:"partition_key,omitempty"`
	// 字段映射
	Mapping []*FieldMapping `protobuf:"bytes,6,rep,name=mapping,proto3" json:"mapping,omitempty"`
	// Sink 特定配置
	Config *SinkConfig `protobuf:"bytes,7,opt,name=config,proto3" json:"config,omitempty"`
	// 源 Topic 名称（可选，通常从事件定义推断）
	SourceTopic string `protobuf:"bytes,8,opt,name=source_topic,json=sourceTopic,proto3" json:"source_topic,omitempty"`
	// 事件数据编码格式，编译时确定
	// 用于 Sink 生成器决定如何解析 data 字段
	EventDataContentType EventDataContentType `protobuf:"varint,9,opt,name=event_data_content_type,json=eventDataContentType,proto3,enum=eventapi.v1.EventDataContentType" json:"event_data_content_type,omitempty"`
	// 是否自动推断 data_path 映射，默认开启
	// 关闭后必须手动写全所有 mapping
	AutoInferDataMapping *bool `protobuf:"varint,10,opt,name=auto_infer_data_mapping,json=autoInferDataMapping,proto3,oneof" json:"auto_infer_data_mapping,omitempty"`
	// 是否自动映射所有字段，默认关闭
	// 开启后自动将所有 Header/Data 字段映射到同名列
	// 可通过 mapping 中的 ignore: true 排除特定字段
	AutoMap       bool `protobuf:"varint,11,opt,name=auto_map,json=autoMap,proto3" json:"auto_map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SinkRule) Reset() {
	*x = SinkRule{}
	mi := &file_eventapi_v1_sink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SinkRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinkRule) ProtoMessage() {}

func (x *SinkRule) ProtoReflect() protoreflect.Message {
	mi := &file_eventapi_v1_sink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinkRule.ProtoReflect.Descriptor instead.
func (*SinkRule) Descriptor() ([]byte, []int) {
	return file_eventapi_v1_sink_proto_rawDescGZIP(), []int{0}
}

func (x *SinkRule) GetTarget() SinkType {
	if x != nil {
		return x.Target
	}
	return SinkType_SINK_TYPE_UNSPECIFIED
}

func (x *SinkRule) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *SinkRule) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *SinkRule) GetPrimaryKey() []string {
	if x != nil {
		return x.PrimaryKey
	}
	return nil
}

func (x *SinkRule) GetPartitionKey() []string {
	if x != nil {
		return x.PartitionKey
	}
	return nil
}

func (x *SinkRule) GetMapping() []*FieldMapping {
	if x != nil {
		return x.Mapping
	}
	return nil
}

func (x *SinkRule) GetConfig() *SinkConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *SinkRule) GetSourceTopic() string {
	if x != nil {
		return x.SourceTopic
	}
	return ""
}

func (x *SinkRule) GetEventDataContentType() EventDataContentType {
	if x != nil {
		return x.EventDataContentType
	}
	return EventDataContentType_CONTENT_TYPE_UNSPECIFIED
}

func (x *SinkRule) GetAutoInferDataMapping() bool {
	if x != nil && x.AutoInferDataMapping != nil {
		return *x.AutoInferDataMapping
	}
	return false
}

func (x *SinkRule) GetAutoMap() bool {
	if x != nil {
		return x.AutoMap
	}
	return false
}

type FieldMapping struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 源字段路径
	//
	// Types that are valid to be assigned to Source:
	//
	//	*FieldMapping_HeaderPath
	//	*FieldMapping_DataPath
	Source isFieldMapping_Source `protobuf_oneof:"source"`
	// 目标列名
	TargetColumn string `protobuf:"bytes,3,opt,name=target_column,json=targetColumn,proto3" json:"target_column,omitempty"`
	// 目标列类型
	Type ColumnType `protobuf:"varint,4,opt,name=type,proto3,enum=eventapi.v1.ColumnType" json:"type,omitempty"`
	// 是否 NOT NULL
	NotNull bool `protobuf:"varint,5,opt,name=not_null,json=notNull,proto3" json:"not_null,omitempty"`
	// 列注释
	Comment string `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	// 是否忽略该字段（不落盘）
	// 仅在 auto_map: true 时有效，用于屏蔽敏感字段
	Ignore        bool `protobuf:"varint,7,opt,name=ignore,proto3" json:"ignore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldMapping) Reset() {
	*x = FieldMapping{}
	mi := &file_eventapi_v1_sink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldMapping) ProtoMessage() {}

func (x *FieldMapping) ProtoReflect() protoreflect.Message {
	mi := &file_eventapi_v1_sink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldMapping.ProtoReflect.Descriptor instead.
func (*FieldMapping) Descriptor() ([]byte, []int) {
	return file_eventapi_v1_sink_proto_rawDescGZIP(), []int{1}
}

func (x *FieldMapping) GetSource() isFieldMapping_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *FieldMapping) GetHeaderPath() string {
	if x != nil {
		if x, ok := x.Source.(*FieldMapping_HeaderPath); ok {
			return x.HeaderPath
		}
	}
	return ""
}

func (x *FieldMapping) GetDataPath() string {
	if x != nil {
		if x, ok := x.Source.(*FieldMapping_DataPath); ok {
			return x.DataPath
		}
	}
	return ""
}

func (x *FieldMapping) GetTargetColumn() string {
	if x != nil {
		return x.TargetColumn
	}
	return ""
}

func (x *FieldMapping) GetType() ColumnType {
	if x != nil {
		return x.Type
	}
	return ColumnType_COLUMN_TYPE_UNSPECIFIED
}

func (x *FieldMapping) GetNotNull() bool {
	if x != nil {
		return x.NotNull
	}
	return false
}

func (x *FieldMapping) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *FieldMapping) GetIgnore() bool {
	if x != nil {
		return x.Ignore
	}
	return false
}

type isFieldMapping_Source interface {
	isFieldMapping_Source()
}

type FieldMapping_HeaderPath struct {
	// 元数据路径: "ce_id", "ce_source", "ce_time"
	// 嵌套 JSON 提取: "$.ce_source.tenant"
	HeaderPath string `protobuf:"bytes,1,opt,name=header_path,json=headerPath,proto3,oneof"`
}

type FieldMapping_DataPath struct {
	// 数据路径: "$.user_id", "$.order.amount"
	// 解析方式由 event_data_content_type 决定
	DataPath string `protobuf:"bytes,2,opt,name=data_path,json=dataPath,proto3,oneof"`
}

func (*FieldMapping_HeaderPath) isFieldMapping_Source() {}

func (*FieldMapping_DataPath) isFieldMapping_Source() {}

type SinkConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Flink checkpoint 间隔（如 "60s"）
	CheckpointInterval string `protobuf:"bytes,1,opt,name=checkpoint_interval,json=checkpointInterval,proto3" json:"checkpoint_interval,omitempty"`
	// 批量大小
	BatchSize int32 `protobuf:"varint,2,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	// Sink 并行度
	Parallelism int32 `protobuf:"varint,3,opt,name=parallelism,proto3" json:"parallelism,omitempty"`
	// 额外属性
	Properties    map[string]string `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SinkConfig) Reset() {
	*x = SinkConfig{}
	mi := &file_eventapi_v1_sink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SinkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinkConfig) ProtoMessage() {}

func (x *SinkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_eventapi_v1_sink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinkConfig.ProtoReflect.Descriptor instead.
func (*SinkConfig) Descriptor() ([]byte, []int) {
	return file_eventapi_v1_sink_proto_rawDescGZIP(), []int{2}
}

func (x *SinkConfig) GetCheckpointInterval() string {
	if x != nil {
		return x.CheckpointInterval
	}
	return ""
}

func (x *SinkConfig) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *SinkConfig) GetParallelism() int32 {
	if x != nil {
		return x.Parallelism
	}
	return 0
}

func (x *SinkConfig) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

var file_eventapi_v1_sink_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*SinkRule)(nil),
		Field:         50102,
		Name:          "eventapi.v1.sink",
		Tag:           "bytes,50102,opt,name=sink",
		Filename:      "eventapi/v1/sink.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// sink 选项编号: 50102
	//
	// optional eventapi.v1.SinkRule sink = 50102;
	E_Sink = &file_eventapi_v1_sink_proto_extTypes[0]
)

var File_eventapi_v1_sink_proto protoreflect.FileDescriptor

const file_eventapi_v1_sink_proto_rawDesc = "" +
	"\n" +
	"\x16eventapi/v1/sink.proto\x12\veventapi.v1\x1a google/protobuf/descriptor.proto\x1a\x1ceventapi/v1/cloudevent.proto\"\x87\x04\n" +
	"\bSinkRule\x12-\n" +
	"\x06target\x18\x01 \x01(\x0e2\x15.eventapi.v1.SinkTypeR\x06target\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05table\x18\x03 \x01(\tR\x05table\x12\x1f\n" +
	"\vprimary_key\x18\x04 \x03(\tR\n" +
	"primaryKey\x12#\n" +
	"\rpartition_key\x18\x05 \x03(\tR\fpartitionKey\x123\n" +
	"\amapping\x18\x06 \x03(\v2\x19.eventapi.v1.FieldMappingR\amapping\x12/\n" +
	"\x06config\x18\a \x01(\v2\x17.eventapi.v1.SinkConfigR\x06config\x12!\n" +
	"\fsource_topic\x18\b \x01(\tR\vsourceTopic\x12X\n" +
	"\x17event_data_content_type\x18\t \x01(\x0e2!.eventapi.v1.EventDataContentTypeR\x14eventDataContentType\x12:\n" +
	"\x17auto_infer_data_mapping\x18\n" +
	" \x01(\bH\x00R\x14autoInferDataMapping\x88\x01\x01\x12\x19\n" +
	"\bauto_map\x18\v \x01(\bR\aautoMapB\x1a\n" +
	"\x18_auto_infer_data_mapping\"\xf9\x01\n" +
	"\fFieldMapping\x12!\n" +
	"\vheader_path\x18\x01 \x01(\tH\x00R\n" +
	"headerPath\x12\x1d\n" +
	"\tdata_path\x18\x02 \x01(\tH\x00R\bdataPath\x12#\n" +
	"\rtarget_column\x18\x03 \x01(\tR\ftargetColumn\x12+\n" +
	"\x04type\x18\x04 \x01(\x0e2\x17.eventapi.v1.ColumnTypeR\x04type\x12\x19\n" +
	"\bnot_null\x18\x05 \x01(\bR\anotNull\x12\x18\n" +
	"\acomment\x18\x06 \x01(\tR\acomment\x12\x16\n" +
	"\x06ignore\x18\a \x01(\bR\x06ignoreB\b\n" +
	"\x06source\"\x86\x02\n" +
	"\n" +
	"SinkConfig\x12/\n" +
	"\x13checkpoint_interval\x18\x01 \x01(\tR\x12checkpointInterval\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x02 \x01(\x05R\tbatchSize\x12 \n" +
	"\vparallelism\x18\x03 \x01(\x05R\vparallelism\x12G\n" +
	"\n" +
	"properties\x18\x04 \x03(\v2'.eventapi.v1.SinkConfig.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x87\x01\n" +
	"\bSinkType\x12\x19\n" +
	"\x15SINK_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SINK_TYPE_STARROCKS\x10\x01\x12\x13\n" +
	"\x0fSINK_TYPE_MYSQL\x10\x02\x12\x18\n" +
	"\x14SINK_TYPE_CLICKHOUSE\x10\x03\x12\x18\n" +
	"\x14SINK_TYPE_POSTGRESQL\x10\x04*\xd5\x01\n" +
	"\n" +
	"ColumnType\x12\x1b\n" +
	"\x17COLUMN_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13COLUMN_TYPE_VARCHAR\x10\x01\x12\x16\n" +
	"\x12COLUMN_TYPE_BIGINT\x10\x02\x12\x19\n" +
	"\x15COLUMN_TYPE_TIMESTAMP\x10\x03\x12\x17\n" +
	"\x13COLUMN_TYPE_DECIMAL\x10\x04\x12\x17\n" +
	"\x13COLUMN_TYPE_BOOLEAN\x10\x05\x12\x14\n" +
	"\x10COLUMN_TYPE_JSON\x10\x06\x12\x16\n" +
	"\x12COLUMN_TYPE_DOUBLE\x10\a:K\n" +
	"\x04sink\x12\x1e.google.protobuf.MethodOptions\x18\xb6\x87\x03 \x01(\v2\x15.eventapi.v1.SinkRuleR\x04sinkB\xa5\x01\n" +
	"\x0fcom.eventapi.v1B\tSinkProtoP\x01Z:github.com/eventapi/eventapi-go/pkg/eventapi/v1;eventapiv1\xa2\x02\x03EXX\xaa\x02\vEventapi.V1\xca\x02\vEventapi\\V1\xe2\x02\x17Eventapi\\V1\\GPBMetadata\xea\x02\fEventapi::V1b\x06proto3"

var (
	file_eventapi_v1_sink_proto_rawDescOnce sync.Once
	file_eventapi_v1_sink_proto_rawDescData []byte
)

func file_eventapi_v1_sink_proto_rawDescGZIP() []byte {
	file_eventapi_v1_sink_proto_rawDescOnce.Do(func() {
		file_eventapi_v1_sink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eventapi_v1_sink_proto_rawDesc), len(file_eventapi_v1_sink_proto_rawDesc)))
	})
	return file_eventapi_v1_sink_proto_rawDescData
}

var file_eventapi_v1_sink_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_eventapi_v1_sink_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_eventapi_v1_sink_proto_goTypes = []any{
	(SinkType)(0),                      // 0: eventapi.v1.SinkType
	(ColumnType)(0),                    // 1: eventapi.v1.ColumnType
	(*SinkRule)(nil),                   // 2: eventapi.v1.SinkRule
	(*FieldMapping)(nil),               // 3: eventapi.v1.FieldMapping
	(*SinkConfig)(nil),                 // 4: eventapi.v1.SinkConfig
	nil,                                // 5: eventapi.v1.SinkConfig.PropertiesEntry
	(EventDataContentType)(0),          // 6: eventapi.v1.EventDataContentType
	(*descriptorpb.MethodOptions)(nil), // 7: google.protobuf.MethodOptions
}
var file_eventapi_v1_sink_proto_depIdxs = []int32{
	0, // 0: eventapi.v1.SinkRule.target:type_name -> eventapi.v1.SinkType
	3, // 1: eventapi.v1.SinkRule.mapping:type_name -> eventapi.v1.FieldMapping
	4, // 2: eventapi.v1.SinkRule.config:type_name -> eventapi.v1.SinkConfig
	6, // 3: eventapi.v1.SinkRule.event_data_content_type:type_name -> eventapi.v1.EventDataContentType
	1, // 4: eventapi.v1.FieldMapping.type:type_name -> eventapi.v1.ColumnType
	5, // 5: eventapi.v1.SinkConfig.properties:type_name -> eventapi.v1.SinkConfig.PropertiesEntry
	7, // 6: eventapi.v1.sink:extendee -> google.protobuf.MethodOptions
	2, // 7: eventapi.v1.sink:type_name -> eventapi.v1.SinkRule
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	7, // [7:8] is the sub-list for extension type_name
	6, // [6:7] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_eventapi_v1_sink_proto_init() }
func file_eventapi_v1_sink_proto_init() {
	if File_eventapi_v1_sink_proto != nil {
		return
	}
	file_eventapi_v1_cloudevent_proto_init()
	file_eventapi_v1_sink_proto_msgTypes[0].OneofWrappers = []any{}
	file_eventapi_v1_sink_proto_msgTypes[1].OneofWrappers = []any{
		(*FieldMapping_HeaderPath)(nil),
		(*FieldMapping_DataPath)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eventapi_v1_sink_proto_rawDesc), len(file_eventapi_v1_sink_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_eventapi_v1_sink_proto_goTypes,
		DependencyIndexes: file_eventapi_v1_sink_proto_depIdxs,
		EnumInfos:         file_eventapi_v1_sink_proto_enumTypes,
		MessageInfos:      file_eventapi_v1_sink_proto_msgTypes,
		ExtensionInfos:    file_eventapi_v1_sink_proto_extTypes,
	}.Build()
	File_eventapi_v1_sink_proto = out.File
	file_eventapi_v1_sink_proto_goTypes = nil
	file_eventapi_v1_sink_proto_depIdxs = nil
}
